# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shuanglin Chen<br>陈双林
url:              //shuanglinchen.com
paginate:         5
baseurl:          /
header:           "http:"
author:
  name:           Shuanglin Chen

gems:
  - jekyll-sitemap

sass:
  style: :compressed
