# Permalinks
permalink:        pretty

# Setup
title:            Shuanglin Chen
title-chinese:    陈双林
url:              //shuanglinchen.com
paginate:         5
baseurl:          /
header:           "http:"
author:
  name:           Shuanglin Chen
  
sass:
  style: :compressed
